[mypy]
python_version = 3.10
mypy_path = .
files = app
namespace_packages = True
explicit_package_bases = True
pretty = True
ignore_missing_imports = True
exclude = (?x)(app/models/clinical/trainer\.py|app/models/image/cnn_model\.py|app/models/image/train_cnn\.py)

